### ISSUE TITLE
 Auto Pointing option for only line-start and line-end timestamps

### ISSUE THREAD

**Issue by PlaylistsTrance** [Juna-Idler/RhythmiKaRuTTE_Spectro#6]
I don't think this is currently possible with auto-pointing. I would like to be able to use auto-pointing to create time markers only at the start and end of all lines.

**Comment by Juna-Idler** [comment]
I didn't expect such a use.
Since it is almost line synchronization, it can be considered as the range of Lyrics TTE.

An easy implementation is to add options to RhythmiKaRu,
It is a matter of consideration to add options that are not expected very much.

Well, there's no reason why you shouldn't use RhythmiKaRu to create line syncs.
Apart from Auto Pointing for karaoke, it may be possible to create Auto Pointing for line synchronization.


そういう用途を想定していなかった。
それってほぼ行同期なので、LyricsTTEの範囲とも考えられる。

簡単に実装するのはRhythmiKaRuにオプションを追加する方法だが、
あまり想定していないオプションを追加するのは検討の対象。

ただまあ、RhythmiKaRuを使って行同期作成をやったらダメな理由もないから、
カラオケ用Auto Pointingとは別にして、行同期用Auto Pointingを作ってもいいかも。

**Comment by PlaylistsTrance** [comment]
The `[start_time]lyric[end_time]` lyrics are considered "2 star Karaoke" according to AutoLyric. It uses the end_time to start the fade-out animation of the line. Currently I am using a regular expression substitution I made to add time markers at the start and end of each line (https://regex101.com/r/m4ftIt/2), but I thought it would be nice if this feature was built in to RhythmiKaRuTTE.
I have only been doing 2-star timing like this since a few days. Before I used to make these in LyricsTTE like you said, but it involves more steps. I would add empty lines after each line to be able to time them, and after I'm done, use a regex to move all of these fade-out timestamps behind the line that came before it.
So, from
```
[00:00.00]Some lyric
[00:02.00]
```
to
```
[00:00.00]Some lyric[00:02.00]
```
As you can see, this is more tedious than using RhythmiKaRuTTE, which supports this syntax already.

**Comment by PlaylistsTrance** [comment]
Thank you, this is great!
